name: CI

on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  test:
    name: "${{ matrix.vim_type }} ${{ matrix.version }} on ${{ matrix.os }}"
    strategy:
      matrix:
        vim_type: ["Vim", "Neovim"]
        version: ["head", "stable"]
        os: ["ubuntu-22.04"]
        include:
          - vim_type: "Vim"
            version: "stable"
            vim_version: "v8.2.5172"
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "Install libfuse2 and upgrade libsqlite3-dev"
        run: |
          sudo apt-get update
          sudo apt-get -y install libfuse2
          # sudo apt-get -y remove libsqlite3-0 libsqlite3-dev
          # apt-cache search libsqlite
          # sudo apt-get -y upgrade libsqlite3-0 | echo -e "Error on upgrading libsqlite3-0"
      - uses: "actions/checkout@v3"
      - name: "Setup Vim"
        id: "vim"
        uses: "thinca/action-setup-vim@v1"
        with:
          vim_version: "${{ matrix.vim_version || matrix.version }}"
          vim_type: "${{ matrix.vim_type }}"
      - name: "Show Vim version"
        run: |
          ${{ steps.vim.outputs.executable }} --version

