name: CI

on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  test:
    name: "${{ matrix.vim_type }} ${{ matrix.version }} on ${{ matrix.os }}"
    strategy:
      matrix:
        vim_type: ["Vim", "Neovim"]
        version: ["head", "stable"]
        os: ["ubuntu-22.04"]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "Install libfuse2"
        run: |
          sudo apt-get update
          sudo apt-get -y install libfuse2
      - uses: "actions/checkout@v3"
      - name: "Setup Vim"
        id: "vim"
        uses: "thinca/action-setup-vim@v1"
        with:
          vim_version: "${{ matrix.version }}"
          vim_type: "${{ matrix.vim_type }}"
      - name: "Show Vim version"
        run: |
          ${{ steps.vim.outputs.executable }} --version
